include:
  - board: assimilator-bt
    shield: imprint_left
  - board: assimilator-bt
    shield: imprint_right
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: totem_right
